### ISSUE TITLE
Add check for event status

### ISSUE THREAD

**Issue by brentdur** [TechAtNYU/eboard-reminders#1]
There's a problem where people don't mark events as "announced" which causes problems with checkins. Let's add a check for events that have no status

**Comment by ethanresnick** [comment]
How do events end up with no status? Doesn't every event default to draft? (If not, they should, right?) 

Also, if people don't mark events as announced, how do we know whether they are in fact complete/ready to be shown in all our UIs? Just assuming that they are ready seems like a bad idea, since I think we want people to be able to add incomplete events to the API — e.g., to claim a date/time before the event details are finalized. So maybe the answer is making the status field more prominent? (See techatnyu/intranet#160.)

**Comment by brentdur** [comment]
@ethanresnick You're right that events with no status shouldn't exist (which really is a intranet problem)

Assuming it's some small amount of time before an un-announced event (let's say a week) and it's not announced that it's worth sending a notification to the creator that it's unannounced. The annoying case is that the event shouldn't be announced and they ignore it. The likely case that if an event is 1 week out and is still a draft (/ doesn't have any status) there's a highly likely hood that it should be fully cancelled or (hopefully) announced.

**Comment by css459** [comment]
Regardless, I'll add a status check within ER. I'll add it as an error flag for an event such that, if an event is approaching and unannounced, it will message the event coordinator explaining that. The issue at large seems to be outside the scope of ER, however.

**Comment by brentdur** [comment]
Let's do if the event is approaching and status is draft or none, ignoring
cancelled and announced events

**Comment by css459** [comment]
Fixed!
